name: CICD
on:
  push:
jobs:
  ci:
    uses: LucasCarioca/workflows/.github/workflows/ci-go.yml@v0.2.0
  release:
    needs: ci
    if: github.ref == 'refs/heads/main'
    uses: LucasCarioca/workflows/.github/workflows/release-homelab.yml@v0.2.8
    with:
      registry: ghcr.io
      image_name: lucascarioca/ibru-api
      deployment: ibru-api-deployment
      container: ibru-api
      namespace: ibru
    secrets:
      kube_config: ${{ secrets.HOME_LAB_KUBE_CONFIG }}
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}